# This code refers to the following exercise by Rosalind https://rosalind.info/problems/ba1a/ (Accessed on September 24th, 2026)

pattern_count <- function(text, pattern) {
  count <- 0
  iteration <- nchar(text)-nchar(pattern) + 1
  
  for (i in 1: iteration ) {
    if (substr(text, i, (nchar(pattern) + i -1 )) == pattern)
    {
      count = count + 1
    }
  }
  print(count)
}

string <- "GCTCTGAAGGAGCTCTGAGCAAGCTCTGATTAGCAAAGCTCTGAGCTCTGAGCTCTGAGCTCTGAGGGCTCTGATGCGCTCTGATGCTCTGAGCTCTGACGCTCTGAGGCTCTGACTGCTCTGAATCTGCAGCTCTGAGCTCTGACAAGCTCTGATACCTGGCCAAGTAGGTTTGGATAGCTCTGAGCTCTGAGCTCTGATGTAAGGGCTCTGAGCTCTGAGAGCTCTGAAGTGAACTCTGCTCTGAGCTCTGAGCCGAGCTCTGAGGAGGCAAGTCGCTCTGAGTTCATCAGCTCTGATTTACAGCTCTGAGGCTCTGAGCTCTGAAGCTCTGACGGGGCTCTGAGCTCTGAGCTCTGAGCTCTGAGCTCTGATGATGCTCTGAGCTCTGAAGCTCTGAGGCTCTGAGCTCTGAGCTCTGATTCTATTCGCTCTGAGCTCTGACAGGCGTGCTCTGAGCAGCTCTGAGAGCTCTGATGAAATCCTGCTCTGAGAGCTCTGAGGGCTCTGAGCTCTGATGCTCTGAGCTCTGAGACGCTCTGAGTCTGCTCTGAGGCTCTGACGCTCTGACTAGGCTCTGAGCTCTGATGCTCTGATCGCTCTGATGCTCTGATGGAAGCATTCGAATTTGCTCTGACGCTCTGAAGCTCTGAATGGCTCTGAGCTCTGACCAGTGCTCTGAAACTAGGCTCTGAAGCTCTGAGCTCTGACCTGCTCTGAGCTCTGAGATTGGTAAGCTCTGAATGCTCTGATGGACGCTCTGACGCTCTGAAGCTCTGAGCTCTGAGCAAGCTCTGAATCGCTCTGATAGCTCTGAGATAGCTCTGAAGTGGCTCTGACGCTCTGAGCGCTCTGACGCTCTGAGCTCTGAAGCTCTGAAGCTCTGACTACGCTCTGAGCTCTGAGGCTCTGACAGCTCTGAGTGCTCTGAGTGCTCTGAGCTCTGAAACGCGCTCTGACGGCTCTGACCTCTATTACCGCTCTGACAAACGCTCTGACTTGCTCTGATATCGCTCTGATTAGCTCTGAGCTCTGAAGATCAGCTCTGAGCTCTGAAA"
pattern <- "GCTCTGAGC"
pattern_count(string,pattern)


